# different values for different screens

[small]
    inner.horizontal = 5
    inner.vertical   = 5
    outer            = 20
    outer_smaller    = 10

[medium]
    inner.horizontal = 10
    inner.vertical   = 10
    outer            = 50
    outer_smaller    = 25

[large]
    inner.horizontal = 10
    inner.vertical   = 10
    outer            = 100
    outer_smaller    = 50


