# different values for different screens

[small]
    inner.horizontal = 15
    inner.vertical   = 15
    outer.left       = 20
    outer.bottom     = 20
    outer.top        = 20
    outer.right      = 20

[medium]
    inner.horizontal = 50
    inner.vertical   = 50
    outer.left       = 50
    outer.bottom     = 50
    outer.top        = 50
    outer.right      = 50

[large]
    inner.horizontal = 15
    inner.vertical   = 15
    outer.left       = 100
    outer.bottom     = 100
    outer.top        = 100
    outer.right      = 100


