# different values for different screens

[small]
    inner.horizontal = 15
    inner.vertical   = 15
    outer.left       = 20
    outer.bottom     = 20
    outer.top        = 20
    outer.right      = 20

[medium]
    inner.horizontal = 25
    inner.vertical   = 25
    outer.left       = 25
    outer.bottom     = 25
    outer.top        = 25
    outer.right      = 25

[large]
    inner.horizontal = 15
    inner.vertical   = 15
    outer.left       = 50
    outer.bottom     = 100
    outer.top        = 100
    outer.right      = 100


